apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: validating-controller.default
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQjhqQ0NBVnNDQVFBd2JERUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdUQWxkQk1SQXdEZ1lEVlFRSApFd2RUWldGMGRHeGxNUlF3RWdZRFZRUUtFd3ROZVNCRGJ5d2dTVzVqTGpFWE1CVUdBMVVFQ3hNT1YybGtaMlYwCklFWmhjbTFsY25NeER6QU5CZ05WQkFNVEJtMTVkWE5sY2pDQm56QU5CZ2txaGtpRzl3MEJBUUVGQUFPQmpRQXcKZ1lrQ2dZRUExYjQ1OTRJMlpzVFhLUnpkUU04cEc5MkRHTEdyeE5WUTNnMFR1ZDAxc0lwTHo5VWd3VHhKS0hLUApBNW5BUEw3aDRFeXFDS0xBdHJtaUhINm5JMVpjKzZKZFhHbDIyVU1LNE5IRXQwbU51RzJuN3FKL21HcUFoM042Ck5UbXlkZzhzdkx5Tm1DejNzbWppU0J1ZDFja1o5T1FKOXhCWC9OV240b1ljS2ZSaTdZTUNBd0VBQWFCR01FUUcKQ1NxR1NJYjNEUUVKRGpFM01EVXdNd1lEVlIwUkJDd3dLb0VRYzI5dFpXOXVaVUJ0ZVdOdkxtTnZiWVlXYUhSMApjSE02THk5c2IyTmhiR2h2YzNRNk9EQTRNREFOQmdrcWhraUc5dzBCQVFzRkFBT0JnUURUQ3FQRFpiRHZtRGpmCkc0SGJEMkdhQVUrYTNaWjNLSUplc1VXa3huaEtHR1BqbXVQQ1lGV1ozSS9uYVRsanVBakIrTlhLaFhXbExsVE4KUlZqZ1lPZ1RiK01lSFNGVHZQejJPaXhiMGpvM2hkT24ydThMOXRyalhEYnk3cjExL1ZQMTdEZE0zRHJNYldrbApsTGs5ZGVzcDgwcGJRczdHVXVPdkFJU1RqbEpVVmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - key agreement
  - server auth