apiVersion: v1
kind: PersistentVolume
metadata:
  name: database
  labels: 
    volume: my-volume
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity: 
    storage: 1Gi
  local:
    path: /mnt/database
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
